### ISSUE TITLE
Add project links to the table

### ISSUE THREAD

**Issue by llyram** [TechWiz-3/scout#12]
Add clickable links of the projects to the displayed table so that the user can directly go to the project instead of searching for the project again on github

**Comment by llyram** [comment]
I would like to be assigned to this issue if possible

**Comment by TechWiz-3** [comment]
Were you thinking of implementing a new column for the link or using Rich to hyperlink the repo name?

**Comment by llyram** [comment]
I was thinking of adding the hyperlink to the repo name and also change the repo name to {user-name}/{repo-name}

**Comment by TechWiz-3** [comment]
How were you thinking of add the hyperlink to the repo name? I know it can be done in Rich but it's not supported by all terminals. Ideally we would get whether hyperlinks are supported or not and based on that change how we display info but not sure if that's possible

**Comment by llyram** [comment]
we can either add hyperlinks to the project name that is supported by some terminals and on other terminals the same code will just render the project name without the hyperlink.

~~Or we can also add another columnt with the full link which will be clickable and is supported by most terminals like this~~
![image](https://user-images.githubusercontent.com/56125520/194694772-253188f2-cd7e-4e44-b8a4-93ee2c2d5387.png)

~~what do you think?~~

Ok, the new colum with full link approach does not work unless the full link is displayed on the terminal and is not truncated for space so this is not viable

**Comment by TechWiz-3** [comment]
ouch, maybe for now keep the owner/repo form and hyperlink it using Rich, most sophisticated terminals should support hyperlinkiing anyways

**Comment by TechWiz-3** [comment]
you'll need to use rich.markdown.Markdown for that i think 🧐 

`Console().print(Markdown("[google](google.com)"))`

**Comment by llyram** [comment]
I'll look into it
