### ISSUE TITLE
Non-token reliance

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#2]
1. Make it so that if the token is not in the env, a warning message will be printed but the program continues normally.
2. When making the request, ensure that the response was valid and not an error due to rate-limiting, if rate-limiting has occurred print an error message warning to use a token and exit

**Comment by the-writer-dev** [comment]
Hey, can I take this one?

**Comment by TechWiz-3** [comment]
Certainly

**Comment by the-writer-dev** [comment]
Thanks, I will be working on it pretty soon!

**Comment by TechWiz-3** [comment]
#24
