### ISSUE TITLE
Adding Contributer's profiles into README.md

### ISSUE THREAD

**Issue by sb-decoder** [TechWiz-3/scout#21]
want to add this. please assign me this task. @TechWiz-3

**Comment by TechWiz-3** [comment]
Manually or using a GH action?

**Comment by sb-decoder** [comment]
If you want this manually then I will do that otherwise using GH action

**Comment by TechWiz-3** [comment]
GH action will be great, can you provide the link or an example of what they'll look like?

**Comment by sb-decoder** [comment]
Ok I will provide you very soon

**Comment by the-writer-dev** [comment]
This would be awesome!
