### ISSUE TITLE
Make viewing of forks count optional

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#26]
Make viewing of forks count optional by adding a `--forks` option. If `--forks` is not used the forks column should not be printed!

**Comment by erdepe-dad** [comment]
Hi @TechWiz-3 . Can I working on this? Thanks 🙏

**Comment by TechWiz-3** [comment]
Sure :) let me know if you need any help

**Comment by erdepe-dad** [comment]
Hi @TechWiz-3 , Already make pull request for this issue #29 . Kindly Please Review The PR. Thanks  🙏🏻

**Comment by TechWiz-3** [comment]
Thank you :)
