### ISSUE TITLE
Make README pypi friendly

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#27]
- [ ] Make README.md Pypi friendly - https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/
- [ ] Add the README to `setup.py`'s `long_description` so it's visible on the project's [pypi page](https://pypi.org/project/gh-scout/0.3.2/) next release

You can test changes on test.pypi.org - if you need help with this let me know :)

**Comment by pragyaasapkota** [comment]
Please assign me on this!!!

**Comment by TechWiz-3** [comment]
Sure :) let me know if you need any help

**Comment by TechWiz-3** [comment]
Are you no longer planning on working on this issue? @Pragya2056

**Comment by pragyaasapkota** [comment]
I will no longer be working on this issue due to some personal reasons. I sincerely apologize. Thank you

**Comment by TechWiz-3** [comment]
Thx for letting me know, all the best to you

**Comment by pratik1424** [comment]
Hey there, 
I have added README to `setup.py`, but I cannot test the changes because PyPI is down for maintenance. 
Let me know if you can test them. I will open a PR if that's possible.

**Comment by TechWiz-3** [comment]
Sure, i'll clone your fork and test it 👍

**Comment by pratik1424** [comment]
Hey there, the site was back up and I was able to test my changes. 
README is now visible as the project description. 
You can check the changes [here](https://test.pypi.org/project/gh-scout-pratik/0.3.3/).

**Comment by TechWiz-3** [comment]
Oh perfect, could you please also edit the `README` to make the example images render-able by pypi, more info [here](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/)

After that, go ahead and submit a PR 👍

**Comment by pratik1424** [comment]
Sure, I am on it.

**Comment by pratik1424** [comment]
I have edited README as desired.
You can look at the update [here](https://test.pypi.org/project/gh-scout-pratik/0.3.4/)

I have submitted a PR for the same. Let me know if anything else needs to be done.
Cheers

**Comment by TechWiz-3** [comment]
Beautiful, great work, thank you
