### ISSUE TITLE
No-colors version

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#3]
Create a simple no-colors version that prints only plain text when taking input and in the projects table.
Have this triggered by `scout --nocolor` and `scout --no-color`

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 i can help with it

**Comment by Prakhar9450** [comment]
Please assign me with this issue

**Comment by TechWiz-3** [comment]
idk what to do now since both of you are asking for it. i will open an new issue for making a default python query with the `--default` flag, how about one of you takes that instead?

**Comment by Manoj0Marmat** [comment]
Sounds good to me

**Comment by TechWiz-3** [comment]
RIP, i forgot this and assigned that issue to someone else, how about this, you take this issue @Manoj0Marmat and the next issue i open i will assign it to @Prakhar9450

**Comment by Manoj0Marmat** [comment]
sure

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 i setup everything but need little help how can i check and test my changes

**Comment by TechWiz-3** [comment]
Just cd into the subdirectory scout `cd scout` and run `python3 main.py` 👍  And then with arguments, so `python3 main.py --nocolor` etc

**Comment by Manoj0Marmat** [comment]
ok got it

**Comment by Manoj0Marmat** [comment]
@TechWiz-3 what about formatting italic, bold?

**Comment by TechWiz-3** [comment]
Yea keep that 👍 thx for asking

**Comment by tejus0** [comment]
Is there anything in this issue that i can contribute in?

**Comment by TechWiz-3** [comment]
There might be some follow up tasks, if there are I'll let you know :)
