### ISSUE TITLE
Add help command for `--forks` option

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#37]
Currently argparse does not have the `--forks option` in it's help command. Add it with the description "additionally display the forks of a repo"

**Comment by rsk2** [comment]
Hi @TechWiz-3, I am interested in working on this. But I see that `--forks` option is already added to the `ArgumentParser` in `scout/main.py`. It has a different description to what you have mentioned above. Therefore, is this ticket about updating that description?

**Comment by TechWiz-3** [comment]
Ayo thanks a lot, apparently i forgot to sync my local version with the repo and I forgot that it had already been added.

If you'd still like to work on a small contribution how about changing the help description for each command to all lowercase as currently the first word of each sentence is captalised>

<img width="567" alt="Screen Shot 2022-11-08 at 1 09 30 am" src="https://user-images.githubusercontent.com/75515581/200331208-f5800007-c07a-44ea-944c-a0b223ab6b37.png">

**Comment by rsk2** [comment]
Ok, I will create a PR with those changes
