### ISSUE TITLE
Change current no-color styling

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#39]
Currently styles are changed manually when the `--no-color` option is used.

However, Rich's [Console API](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console) has an argument which can achieve this called `no_color`.

The task is to remove the manual styling and simply change the console definition with the argument `no_color=True` if the `--no-color` option is used

**Comment by abedaton** [comment]
I attempted to solve this in #40 , can you have a look ?
