### ISSUE TITLE
Add Rich rule

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#4]
Add a beautiful [rule](https://rich.readthedocs.io/en/latest/reference/rule.html) at the start of the CLI. The rule should contain the text "Your personal opensource Scout" and the text should be aligned to center.

A good example [here](https://github.com/guedesfelipe/pls-cli). Also star that repo because it's poggers.

**Comment by Dinoosawruss** [comment]
Sounds good could I get assigned to this?

**Comment by TechWiz-3** [comment]
Sorry already been solved, check out some other ones tho 👍 I'm adding some new ones now
