### ISSUE TITLE
Except Keyboard Interrupt for inputs

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#7]
Currently, when getting user inputs, if the user interrupts the prompts with `Ctrl-C`, the standard `KeyboardInterrupt` message occurs!

In the `get_url()` function add an exception for KeyboardInerrupt and put a nice message like *Farewell my friend, beware the crickets*. Then print a new line to the console and exit.

<img width="811" alt="Screen Shot 2022-10-08 at 11 56 22 am" src="https://user-images.githubusercontent.com/75515581/194679449-28ae3eee-49c1-4452-b1c7-a81a85b448e8.png">

**Comment by Kiinitix** [comment]
can you please assign this to me?
