### ISSUE TITLE
CI and tests

### ISSUE THREAD

**Issue by TechWiz-3** [TechWiz-3/scout#9]
Add `flake8` linting with GitHub actions as well as some automated tests for the CLI

**Comment by JoelLau** [comment]
hi @TechWiz-3, may I take this up?

**Comment by TechWiz-3** [comment]
certainly

**Comment by TechWiz-3** [comment]
Any updates Joel? No pressure, just following up

**Comment by JoelLau** [comment]
sorry for the slow response! had a influx of work at my day job, but its good now.

should be able to open a PR this weekend 👍

**Comment by JoelLau** [comment]
opened a PR #35 , lmk if it makes sense to you (:

**Comment by TechWiz-3** [comment]
thanks a lot :)
